language: objective-c

install:
  - bash build-libssl.sh --noverify --i386only
  - bash build-libevent.sh --noverify --i386only
  - bash build-libtor.sh --noverify --i386only
  - pod install

script:
  - xctool -workspace OnionKit.xcworkspace -scheme OnionKitTestsiOS -sdk iphonesimulator8.0 -arch i386 test